name: Build Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.WERFENTOUCHCLIENTTOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.14.0

      - name: Install dependencies npm
        run: npm install

      - name: update react-scripts
        run: npm update react-scripts

      - name: Install craco
        run: npm install @craco/craco@0.0.3

      - name: craco build
        run: npm run build

      - name: Build electron-builder
        run: npm run electron-builder -w

      - name: Copy to Docs
        run: cp dist/*.exe docs/

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: docs/*.exe
